"""Created buyer and seller table migrations. Finally!

Revision ID: b9fb5df4bbf5
Revises: 
Create Date: 2024-08-26 19:57:06.565876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fb5df4bbf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_no', sa.Integer(), nullable=False),
    sa.Column('e_mail', sa.String(), nullable=True),
    sa.Column('seeking_since', sa.Date(), nullable=True),
    sa.Column('actively_seeking', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_no', sa.Integer(), nullable=False),
    sa.Column('e_mail', sa.String(), nullable=True),
    sa.Column('Plot_Add', sa.Text(), nullable=True),
    sa.Column('Expected_Price', sa.Integer(), nullable=True),
    sa.Column('Plot_Details', sa.Text(), nullable=False),
    sa.Column('seeking_from', sa.Date(), nullable=True),
    sa.Column('actively_seeking', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Plot_Add')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Seller')
    op.drop_table('Buyer')
    # ### end Alembic commands ###
